backend:
  name: git-gateway
  branch: main # Branch to update

media_folder: "src/assets/photos/uploads"
public_folder: "/assets/photos/uploads"

collections:
  - name: "items"
    label: "Prestations"
    file: "src/_data/services.json"
    fields:
      - label: Liste des prestations
        name: items 
        widget : list
        allow_add: true
        fields:
          - { label : "Nom", name: "title", widget: "string" }
          - { label : "Prix", name: "price", widget: "string" }
          - { label : "Description", name: "description", widget: "string" }
  - name: "header"
    label: "Barre de navigation"
    file: "src/_data/header.json"
    fields:
      - { name: "logo", label: "Logo" }
      - { name: "home-nav", label: "titre Accueil" }
      - { name: "gallery-nav", label: "titre Gallerie photos" }
      - { name: "services-nav", label: "titre Prestations" }
      - { name: "contact-nav", label: "titre Contact" }