backend:
  name: git-gateway
  branch: main # Branch to update

media_folder: "src/assets/photos/uploads"
public_folder: "/assets/photos/uploads"

collections:
  - name: "service"
    label: "Service"
    folder: "src/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tags", name: "tags", widget: "hidden", default: "service" }
      - { label : "Title", name: "title", widget: "string" }
      - { label : "Price", name: "price", widget: "string" }
      - { label : "Description", name: "description", widget: "string" }
  
  - name: "config"
    label: "Configuration"
    files:
      - name: "header"
        label: "Header"
        file: "src/_data/header.json"
        fields:
          - { name: "logo", label: "Logo" }
          - { name: "home-nav", label: "Home title" }
          - { name: "gallery-nav", label: "Gallery title" }
          - { name: "services-nav", label: "Services title" }
          - { name: "services-collections-nav", label: "Services collection title" }
          - { name: "contact-nav", label: "Contact title" }
      - name: "items"
        label: "Services"
        widget : list
        file: "src/_data/services.json"
        allow_add: true
        fields:
          - { label : "Title", name: "title", widget: "string" }
          - { label : "Price", name: "price", widget: "string" }
          - { label : "Description", name: "description", widget: "string" }
