backend:
  name: git-gateway
  branch: main # Branch to update

media_folder: "src/assets/photos"
public_folder: "/assets/photos"

collections:
  - name: "portrait_photos"
    label: "Photo de portrait"
    folder: "src/photos"
    create : true
    filter: {field: "Catégorie", value: "portrait"}
    fields:
      - { label: "Chemin complet", name: "url", widget: "image"}
      - { label: "Catégorie", name: "category", widget: "select", options: ["portrait", "couple"]}
  - name: "couple_photos"
    label: "Photo de couple"
    folder: "src/photos"
    create : true
    filter: {field: "Catégorie", value: "couple"}
    fields:
      - { label: "Chemin complet", name: "url", widget: "image"}
      - { label: "Catégorie", name: "category", widget: "select", options: ["portrait", "couple"]}    
  - label: "Paramètres de configuration"
    name: "settings"
    files:
      - name: "header"
        label: "Barre de navigation"
        file: "src/_data/header.json"
        fields:
          - { name: "logo", label: "Logo", widget: "image" }
          - { name: "home-nav", label: "titre Accueil" }
          - { name: "gallery-nav", label: "titre Gallerie photos" }
          - { name: "services-nav", label: "titre Prestations" }
          - { name: "contact-nav", label: "titre Contact" }
      - name: "services"
        label: "Prestations et tarifs"
        file: "src/_data/services.json"
        fields:
          - label: "Prestation"
            name: services
            widget : list
            allow_add: true
            fields:
              - { label : "Nom", name: "title", widget: "string" }
              - { label : "Prix", name: "price", widget: "string" }
              - { label : "Description", name: "description", widget: "string" }