backend:
  name: git-gateway
  branch: main # Branch to update

media_folder: "src/assets/photos"
public_folder: "/assets/photos"

collections:
  - name: "photos"
    label: "Gallerie photos"
    folder: "src/photos"
    slug: "{{slug}}"
    create : false
    fields:
      - { label: "Catégorie", name: "category", widget: "string"}
      - { label: "Chemin complet", name: "url", widget: "image"}
  - label: "Paramètres de configuration"
    name: "settings"
    files:
      - name: "header"
        label: "Barre de navigation"
        file: "src/_data/header.json"
        fields:
          - { name: "logo", label: "Logo" }
          - { name: "home-nav", label: "titre Accueil" }
          - { name: "gallery-nav", label: "titre Gallerie photos" }
          - { name: "services-nav", label: "titre Prestations" }
          - { name: "contact-nav", label: "titre Contact" }
      - name: "services"
        label: "Prestations et tarifs"
        file: "src/_data/services.json"
        fields:
          - label: Items
            name: items 
            widget : list
            allow_add: true
            fields:
              - { label : "Nom", name: "title", widget: "string" }
              - { label : "Prix", name: "price", widget: "string" }
              - { label : "Description", name: "description", widget: "string" }