backend:
  name: git-gateway
  branch: main # Branch to update

media_folder: "src/assets/photos"
public_folder: "/assets/photos"

collections:
  - name: "settings"
    label: "Paramètres de configuration"
    files:
      - name: "header"
        label: "Barre de navigation"
        file: "src/_data/header.json"
        fields:
          - { name: "logo", label: "Logo", widget: "image" }
          - { name: "home-nav", label: "titre Accueil" }
          - { name: "gallery-nav", label: "titre Gallerie photos" }
          - { name: "services-nav", label: "titre Prestations" }
          - { name: "contact-nav", label: "titre Contact" }
      - name: "portrait_photos"
        label: "Photos Portrait"
        file: "src/_data/photos_portraits.json"
        fields:
          - { label: "Catégorie", name: "category", widget: "string", value: "portrait" }
          - { label: "Titre Catégorie", name: "h2-title", widget: "string" }
          - { label: "Photos", name: items, widget: list, allow_add: true, field: { label: "Image", name: "path" }}
      - name: "couple_photos"
        label: "Photos Couple"
        file: "src/_data/photos_couples.json"
        fields:
          - { label: "Catégorie", name: "category", widget: "string", value: "couple" }
          - { label: "Titre Catégorie", name: "h2-title", widget: "string" }
          - { label: "Photos", name: items, widget: list, allow_add: true, field: { label: "Image", name: "path" }}
      - name: "marriage_photos"
        label: "Photos Mariage"
        file: "src/_data/photos_marriages.json"
        fields:
          - { label: "Catégorie", name: "category", widget: "string", value: "marriage" }
          - { label: "Titre Catégorie", name: "h2-title", widget: "string" }
          - { label: "Photos", name: items, widget: list, allow_add: true, field: { label: "Image", name: "path" }}
      - name: "pregnancy_photos"
        label: "Photos Grossesse"
        file: "src/_data/photos_pregnancies.json"
        fields:
          - { label: "Catégorie", name: "category", widget: "string", value: "pregnancy" }
          - { label: "Titre Catégorie", name: "h2-title", widget: "string" }
          - { label: "Photos", name: items, widget: list, allow_add: true, field: { label: "Image", name: "path" }}
      - name: "baby_photos"
        label: "Photos Bébé"
        file: "src/_data/photos_babies.json"
        fields:
          - { label: "Catégorie", name: "category", widget: "string", value: "baby" }
          - { label: "Titre Catégorie", name: "h2-title", widget: "string" }
          - { label: "Photos", name: items, widget: list, allow_add: true, field: { label: "Image", name: "path" }}
      - name: "baptism_photos"
        label: "Photos Baptême"
        file: "src/_data/photos_baptismes.json"
        fields:
          - { label: "Catégorie", name: "category", widget: "string", value: "baptism" }
          - { label: "Titre Catégorie", name: "h2-title", widget: "string" }
          - { label: "Photos", name: items, widget: list, allow_add: true, field: { label: "Image", name: "path" }}
      - name: "family_photos"
        label: "Photos Famille"
        file: "src/_data/photos_families.json"
        fields:
          - { label: "Catégorie", name: "category", widget: "string", value: "family" }
          - { label: "Titre Catégorie", name: "h2-title", widget: "string" }
          - { label: "Photos", name: items, widget: list, allow_add: true, field: { label: "Image", name: "path" }}
      - name: "services"
        label: "Prestations et tarifs"
        file: "src/_data/services.json"
        fields:
          - label: "Prestation"
            name: items
            widget: list
            allow_add: true
            fields:
              - { label : "Nom", name: "title", widget: "string" }
              - { label : "Prix", name: "price", widget: "string" }
              - { label : "Description", name: "description", widget: "string" }