backend:
  name: git-gateway
  branch: main # Branch to update

media_folder: "src/assets/images"

collections:
  - name: "settings"
    label: "Paramètres généraux du site"
    files:
      - name: "header"
        label: "Barre de navigation"
        file: "src/_data/header.json"
        fields:
          - { name: "logo", label: "Logo", widget: "image" }
          - { name: "home-nav", label: "titre Accueil" }
          - { name: "gallery-nav", label: "titre Gallerie photos" }
          - { name: "services-nav", label: "titre Prestations" }
          - { name: "contact-nav", label: "titre Contact" }
  - name: "photos-gallery"
    label: "Galleries de photos"
    files: 
      - name: "portrait_photos"
        label: "Gallerie Portrait"
        file: "src/_data/photos_portraits.json"
        fields:
          - label: "Photos"
            name: items
            widget: list
            allow_add: true
            fields: 
              - { label: "Image", name: "image", widget: "image" }
      - name: "couple_photos"
        label: "Gallerie Couple"
        file: "src/_data/photos_couples.json"
        fields:
          - label: "Photos"
            name: items
            widget: list
            allow_add: true
            fields: 
              - { label: "Image", name: "image", widget: "image" }
      - name: "marriage_photos"
        label: "Gallerie Mariage"
        file: "src/_data/photos_marriages.json"
        fields:
          - label: "Photos"
            name: items
            widget: list
            allow_add: true
            fields: 
              - { label: "Image", name: "image", widget: "image" }
      - name: "pregnancy_photos"
        label: "Gallerie Grossesse"
        file: "src/_data/photos_pregnancies.json"
        fields:
          - label: "Photos"
            name: items
            widget: list
            allow_add: true
            fields: 
              - { label: "Image", name: "image", widget: "image" }
      - name: "baby_photos"
        label: "Gallerie Bébé"
        file: "src/_data/photos_babies.json"
        fields:
          - label: "Photos"
            name: items
            widget: list
            allow_add: true
            fields: 
              - { label: "Image", name: "image", widget: "image" }
      - name: "baptism_photos"
        label: "Gallerie Baptême"
        file: "src/_data/photos_baptismes.json"
        fields:
          - label: "Photos"
            name: items
            widget: list
            allow_add: true
            fields: 
              - { label: "Image", name: "image", widget: "image" }
      - name: "family_photos"
        label: "Gallerie Famille"
        file: "src/_data/photos_families.json"
        fields:
          - label: "Photos"
            name: items
            widget: list
            allow_add: true
            fields: 
              - { label: "Image", name: "image", widget: "image" }
  - name: "services"
    label: "Prestations et tarifs"
    files:
      - name: "services"
        label: "Prestations"
        file: "src/_data/services.json"
        fields:
          - label: "Prestations"
            name: items
            widget: list
            allow_add: true
            fields:
              - { label : "Nom", name: "title", widget: "string" }
              - { label : "Prix", name: "price", widget: "string" }
              - { label : "Description", name: "description", widget: "string" }