backend:
  name: git-gateway
  branch: main # Branch to update

media_folder: "src/assets/photos"
public_folder: "/assets/photos"

collections:
  - label: "Paramètres de configuration"
    name: "settings"
    files:
      - name: "items"
        label: "Prestations et tarifs"
        file: "src/_data/services.json"
        fields:
          - label: Items
            name: items 
            widget : list
            allow_add: true
            fields:
              - { label : "Nom", name: "title", widget: "string" }
              - { label : "Prix", name: "price", widget: "string" }
              - { label : "Description", name: "description", widget: "string" }
      - name: "photos"
        label: "Gallerie Photos"
        file: "src/_data/photos.json"
        fields:
          - label: Catégorie Portrait
            name: portrait
            fields:
              - { label : "Titre", name: "h2-title", widget: "string" }
              - { label : "Photos", name: "items", widget: list, allow_add: true, field: {label: "Chemin complet", name: "path", widget: "string"}}
          - label: Catégorie Couple
            name: couple
            fields:
              - { label : "Titre", name: "h2-title", widget: "string" }
              - { label : "Photos", name: "items", widget: list, allow_add: true, field: {label: "Chemin complet", name: "path", widget: "string"}}
      - name: "header"
        label: "Barre de navigation"
        file: "src/_data/header.json"
        fields:
          - { name: "logo", label: "Logo" }
          - { name: "home-nav", label: "titre Accueil" }
          - { name: "gallery-nav", label: "titre Gallerie photos" }
          - { name: "services-nav", label: "titre Prestations" }
          - { name: "contact-nav", label: "titre Contact" }