backend:
  name: git-gateway
  branch: main # Branch to update

media_folder: "src/assets/images"

collections:
  - name: "settings"
    label: "Paramètres généraux du site"
    files:
      - name: "header"
        label: "Barre de navigation"
        file: "src/_data/header.json"
        fields:
          - { name: "logo", label: "Logo", widget: "image" }
          - { name: "home-nav", label: "titre Accueil" }
          - { name: "gallery-nav", label: "titre Galerie photos" }
          - { name: "services-nav", label: "titre Prestations" }
          - { name: "contact-nav", label: "titre Contact" }
          - { name: "facebook-logo", label: "Logo Facebook", widget: "image" }
          - { name: "facebook-page", label: "Page Facebook", widget: "string" }
          - { name: "instagram-logo", label: "Logo Instagram", widget: "image" }
          - { name: "instagram-page", label: "Page Instagram", widget: "string" }
  - name: "photos-gallery"
    label: "Galeries de photos"
    description: "Pour chaque galerie, vous allez pouvoir visualiser les photos de la galerie, ajouter des photos ou en supprimer"
    files: 
      - name: "portrait_photos"
        label: "Galerie Portrait"
        file: "src/_data/photos_portraits.json"
        fields:
          - label: "Photos"
            name: items
            widget: list
            allow_add: true
            fields: 
              - { label: "Photo", name: "image", widget: "image" }
      - name: "couple_photos"
        label: "Galerie Couple"
        file: "src/_data/photos_couples.json"
        fields:
          - label: "Photos"
            name: items
            widget: list
            allow_add: true
            fields: 
              - { label: "Photo", name: "image", widget: "image" }
      - name: "marriage_photos"
        label: "Galerie Mariage"
        file: "src/_data/photos_marriages.json"
        fields:
          - label: "Photos"
            name: items
            widget: list
            allow_add: true
            fields: 
              - { label: "Photo", name: "image", widget: "image" }
      - name: "pregnancy_photos"
        label: "Galerie Grossesse"
        file: "src/_data/photos_pregnancies.json"
        fields:
          - label: "Photos"
            name: items
            widget: list
            allow_add: true
            fields: 
              - { label: "Photo", name: "image", widget: "image" }
      - name: "baby_photos"
        label: "Galerie Bébé"
        file: "src/_data/photos_babies.json"
        fields:
          - label: "Photos"
            name: items
            widget: list
            allow_add: true
            fields: 
              - { label: "Photo", name: "image", widget: "image" }
      - name: "baptism_photos"
        label: "Galerie Baptême"
        file: "src/_data/photos_baptismes.json"
        fields:
          - label: "Photos"
            name: items
            widget: list
            allow_add: true
            fields: 
              - { label: "Photo", name: "image", widget: "image" }
      - name: "family_photos"
        label: "Galerie Famille"
        file: "src/_data/photos_families.json"
        fields:
          - label: "Photos"
            name: items
            widget: list
            allow_add: true
            fields: 
              - { label: "Photo", name: "image", widget: "image" }
  - name: "services"
    label: "Prestations et tarifs"
    description: "Vous pouvez mettre à jour les prestations et tarifs, en créer, en modifier ou en supprimer." 
    files:
      - name: "services"
        label: "Liste des prestations"
        file: "src/_data/services.json"
        fields:
          - label: "Prestations"
            name: items
            widget: list
            allow_add: true
            fields:
              - { label : "Nom", name: "title", widget: "string" }
              - { label : "Prix", name: "price", widget: "string" }
              - { label : "Description", name: "description", widget: "string" }
  - name: "pages"
    label: "Pages"
    files:
      - name: "home-page"
        label: "Page d'accueil"
        file: "src/_data/page_home.json"
        fields: 
          - { label : "Titre", name: "hero-title", widget: "string" }
          - { label : "Photo", name: "hero-photo", widget: "image" }
      - name: "gallery-page"
        label: "Page Galerie Photos"
        file: "src/_data/page_gallery.json"
        fields: 
          - { label : "Titre Page h1", name: "page-title", widget: "string" }
          - { label : "Phrase 1", name: "sentence1", widget: "string", required: false }
          - { label : "Phrase 2", name: "sentence2", widget: "string", required: false }
          - { label : "Phrase 3", name: "sentence3", widget: "string", required: false }
          - { label : "Texte du menu déroulant", name: "dropdown-text", widget: "string" }

          - { label : "Titre h2 Portrait", name: "portrait-title", widget: "string" }
          - { label : "Titre h2 Couple", name: "couple-title", widget: "string" }
          - { label : "Titre h2 Mariage", name: "marriage-title", widget: "string" }
          - { label : "Titre h2 Grossesse", name: "pregnancy-title", widget: "string" }
          - { label : "Titre h2 Bébé", name: "baby-title", widget: "string" }
          - { label : "Titre h2 Baptême", name: "baptism-title", widget: "string" }
          - { label : "Titre h2 Famille", name: "family-title", widget: "string" }
      - name: "services-page"
        label: "Page Prestations"
        file: "src/_data/page_services.json"
        fields: 
          - { label : "Titre Page h1", name: "page-title", widget: "string" }
      - name: "contact-page"
        label: "Page Contact"
        file: "src/_data/page_contact.json"
        fields: 
          - { label : "Titre Page h1", name: "page-title", widget: "string" }

          - { label : "Etiquette Nom", name: "firstname-label", widget: "string" }
          - { label : "Etiquette Prénom", name: "lastname-label", widget: "string" }
          - { label : "Etiquette Mail", name: "email-label", widget: "string" }
          - { label : "Etiquette Message", name: "msg-label", widget: "string" }

          - { label : "Message d'erreur Nom", name: "firstname-error", widget: "string" }
          - { label : "Message d'erreur Prénom", name: "lastname-error", widget: "string" }
          - { label : "Message d'erreur Email", name: "email-error", widget: "string" }
          - { label : "Message d'erreur Message", name: "msg-error", widget: "string" }

          - { label : "Texte du bouton", name: "button-text", widget: "string" }
